<!-- Generated by Trae Work -->
<!--
  移动端悬浮 Dock 底栏 v4 - iOS 26 Liquid Glass 风格
  真正悬浮特征：
  1. 四周大留白：底部32px + safe area，左右各24px，不贴边
  2. Dock宽度自适应内容，不撑满屏幕宽度（fit-content）
  3. 真正Liquid Glass：L1薄玻璃0.08填充 + 亮边0.65 + blur12px + 柔影
  4. 精致SVG线性图标（学术雅致，绝对不用emoji）
  5. JS+ResizeObserver动态测量，滑动药丸透镜永远精确
  6. iOS级spring弹性动效，点击有按压反馈
-->
<template>
  <nav class="tabbar" v-if="isMobile">
    <div class="tabbar-dock" ref="barRef">
      <!-- 滑动药丸透镜：选中项的金色玻璃透镜 -->
      <div
        class="tab-lens"
        :style="{ transform: `translate3d(${pill.x}px, 0, 0)`, width: `${pill.w}px` }"
      />
      <button
        v-for="(t, i) in tabs"
        :key="t.to"
        class="tab"
        :class="{ on: activeIndex === i }"
        :ref="el => setTabRef(el, i)"
        @click="go(t.to)"
      >
        <span class="t-ic-wrap">
          <svg class="t-ic" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">
            <component :is="t.icon" />
          </svg>
        </span>
        <span class="t-lb">{{ t.lb }}</span>
      </button>
    </div>
  </nav>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, nextTick, watch, h } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useUserStore } from '@/store/user'

const route = useRoute()
const router = useRouter()
const user = useUserStore()
const barRef = ref<HTMLElement | null>(null)
const tabRefs = ref<(HTMLElement | null)[]>([])

const setTabRef = (el: any, i: number) => {
  if (el) tabRefs.value[i] = el
}

// SVG 线性图标 - 学术雅致风格，2px stroke，圆角线帽
const IconHome = () => [
  h('path', { d: 'M3 10.5L12 3l9 7.5' }),
  h('path', { d: 'M5 9.5V20a1 1 0 001 1h4v-6h4v6h4a1 1 0 001-1V9.5' })
]
const IconBook = () => [
  h('path', { d: 'M4 19.5v-15A2.5 2.5 0 016.5 2H20v18H6.5A2.5 2.5 0 004 22.5' }),
  h('path', { d: 'M4 19.5A2.5 2.5 0 016.5 17H20' })
]
const IconCompass = () => [
  h('circle', { cx: '12', cy: '12', r: '9' }),
  h('polygon', { points: '15.5 8.5 13.5 13.5 8.5 15.5 10.5 10.5 15.5 8.5' })
]
const IconUser = () => [
  h('path', { d: 'M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2' }),
  h('circle', { cx: '12', cy: '7', r: '3.5' })
]
const IconSettings = () => [
  h('circle', { cx: '12', cy: '12', r: '2.5' }),
  h('path', { d: 'M19.4 15a1.65 1.65 0 00.33 1.82l.06.06a2 2 0 01-2.83 2.83l-.06-.06a1.65 1.65 0 00-1.82-.33 1.65 1.65 0 00-1 1.51V21a2 2 0 01-4 0v-.09A1.65 1.65 0 009 19.4a1.65 1.65 0 00-1.82.33l-.06.06a2 2 0 01-2.83-2.83l.06-.06a1.65 1.65 0 00.33-1.82 1.65 1.65 0 00-1.51-1H3a2 2 0 010-4h.09A1.65 1.65 0 004.6 9a1.65 1.65 0 00-.33-1.82l-.06-.06a2 2 0 012.83-2.83l.06.06a1.65 1.65 0 001.82.33H9a1.65 1.65 0 001-1.51V3a2 2 0 014 0v.09a1.65 1.65 0 001 1.51 1.65 1.65 0 001.82-.33l.06-.06a2 2 0 012.83 2.83l-.06.06a1.65 1.65 0 00-.33 1.82V9a1.65 1.65 0 001.51 1H21a2 2 0 010 4h-.09a1.65 1.65 0 00-1.51 1z' })
]

const allTabs = [
  { to: '/', lb: '首页', icon: IconHome, roles: ['SUPER_ADMIN','TEACHER','STUDENT'] },
  { to: '/subjects', lb: '科目', icon: IconBook, roles: ['SUPER_ADMIN','TEACHER','STUDENT'] },
  { to: '/guide', lb: '指南', icon: IconCompass, roles: ['SUPER_ADMIN','TEACHER','STUDENT'] },
  { to: '/profile', lb: '我的', icon: IconUser, roles: ['SUPER_ADMIN','TEACHER','STUDENT'] },
  { to: '/admin', lb: '管理', icon: IconSettings, roles: ['SUPER_ADMIN','TEACHER'] },
]

const tabs = computed(() => allTabs.filter(t => t.roles.includes((user as any).role || 'STUDENT')))

const activeIndex = computed(() => {
  const p = route.path
  const idx = tabs.value.findIndex(t => {
    if (t.to === '/') return p === '/'
    return p.startsWith(t.to)
  })
  return idx >= 0 ? idx : 0
})

// 药丸透镜位置 - 精确测量
const pill = ref({ x: 0, w: 0 })

const measurePill = () => {
  if (!barRef.value) return
  const bar = barRef.value
  const activeEl = tabRefs.value[activeIndex.value]
  if (!activeEl) return

  const barRect = bar.getBoundingClientRect()
  const elRect = activeEl.getBoundingClientRect()

  // 透镜比tab略小，形成聚焦效果
  const x = elRect.left - barRect.left
  const w = elRect.width - 12
  const offsetX = (elRect.width - w) / 2

  pill.value = { x: x + offsetX, w: w }
}

watch(activeIndex, () => { nextTick(() => measurePill()) })

let ro: ResizeObserver | null = null
const isMobile = ref(false)

const check = () => { isMobile.value = window.innerWidth <= 768 }

onMounted(() => {
  check()
  const onResize = () => { check(); measurePill() }
  window.addEventListener('resize', onResize)
  nextTick(() => {
    measurePill()
    if (window.ResizeObserver && barRef.value) {
      ro = new ResizeObserver(() => measurePill())
      ro.observe(barRef.value)
      tabRefs.value.forEach(el => el && ro?.observe(el))
    }
  })
})

onUnmounted(() => {
  window.removeEventListener('resize', check)
  ro?.disconnect()
})

function go(to: string) { router.push(to) }
</script>

<style scoped>
.tabbar {
  display: block;
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  z-index: 200;
  /* ===== 真正悬浮：四周大留白，不贴边 =====
     底部：32px + safe area（不是贴底）
     左右：各24px留白（dock在中间飘着）
     这才是iOS 26 floating capsule的精髓 */
  padding: 0 24px calc(32px + env(safe-area-inset-bottom));
  pointer-events: none;
}

.tabbar-dock {
  pointer-events: auto;
  position: relative;
  display: flex;
  align-items: center;
  justify-content: center;
  /* 宽度自适应内容，不撑满！min-width保证5个tab能放下，max-width限制不会太宽 */
  width: fit-content;
  min-width: 260px;
  max-width: 340px;
  height: 58px;
  margin: 0 auto;
  padding: 4px 5px;
  border-radius: 29px;
  /* ===== Liquid Glass L1导航层玻璃（铁律14）=====
     填充：0.08极薄（不是白瓷块0.5+）
     亮边：0.65白边（玻璃边缘反光，不是inset高光）
     blur：12px（透镜感，不是大模糊磨砂）
     阴影：柔影三层，只"浮"不"框" */
  background: linear-gradient(160deg, rgba(255,255,255,0.08), rgba(255,252,245,0.06));
  -webkit-backdrop-filter: blur(12px) saturate(180%);
  backdrop-filter: blur(12px) saturate(180%);
  box-shadow:
    0 0.5px 0 0 rgba(255,255,255,0.65),
    0 1px 1.5px rgba(120,90,30,0.02),
    0 6px 20px -8px rgba(120,90,30,0.08),
    0 20px 48px -20px rgba(120,90,30,0.12);
}

/* 滑动透镜：金色玻璃聚焦效果，选中项的"透镜" */
.tab-lens {
  position: absolute;
  top: 4px;
  left: 5px;
  height: 50px;
  border-radius: 25px;
  background: linear-gradient(145deg,
    rgba(var(--zg-primary-rgb, 186,117,23), 0.10),
    rgba(var(--zg-accent-rgb, 232,213,163), 0.06)
  );
  box-shadow:
    0 0.5px 0 0 rgba(255,255,255,0.5),
    0 1px 2px rgba(var(--zg-primary-rgb, 186,117,23), 0.06),
    0 4px 12px -4px rgba(var(--zg-primary-rgb, 186,117,23), 0.10);
  transform: translate3d(0, 0, 0);
  transition: transform 0.55s cubic-bezier(0.34, 1.56, 0.64, 1),
              width 0.55s cubic-bezier(0.34, 1.56, 0.64, 1);
  z-index: 0;
  pointer-events: none;
  will-change: transform, width;
}

.tab {
  position: relative;
  z-index: 1;
  flex: 1;
  min-width: 0;
  height: 50px;
  border: none;
  background: transparent;
  cursor: pointer;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 2px;
  color: var(--zg-text-dim);
  opacity: 0.7;
  transition: color 0.3s cubic-bezier(0.22, 1, 0.36, 1),
              opacity 0.3s ease,
              transform 0.4s cubic-bezier(0.34, 1.56, 0.64, 1);
  -webkit-tap-highlight-color: transparent;
  user-select: none;
  padding: 0 2px;
  font-family: inherit;
}

.t-ic-wrap {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 24px;
  height: 24px;
  transition: transform 0.4s cubic-bezier(0.34, 1.56, 0.64, 1);
}

.t-ic {
  width: 22px;
  height: 22px;
  transition: transform 0.4s cubic-bezier(0.34, 1.56, 0.64, 1),
              opacity 0.3s ease,
              stroke-width 0.3s ease;
}

.t-lb {
  font-size: 10px;
  font-weight: 500;
  line-height: 1;
  letter-spacing: 0.02em;
  transition: font-weight 0.3s ease, color 0.3s ease,
              transform 0.4s cubic-bezier(0.34, 1.56, 0.64, 1);
}

.tab.on {
  color: var(--zg-primary);
  opacity: 1;
}

.tab.on .t-ic-wrap {
  transform: translateY(-1px);
}

.tab.on .t-ic {
  transform: scale(1.08);
  stroke-width: 2.2;
}

.tab.on .t-lb {
  font-weight: 600;
}

.tab:active {
  transform: scale(0.92);
}

/* ===== 深色模式：温润暖黑玻璃 ===== */
.zg-inkgold-dark .tabbar-dock {
  background: linear-gradient(160deg, rgba(40,33,22,0.18), rgba(28,22,14,0.10));
  box-shadow:
    0 0.5px 0 0 rgba(255,243,214,0.15),
    0 1px 2px rgba(0,0,0,0.10),
    0 6px 20px -8px rgba(0,0,0,0.25),
    0 20px 48px -20px rgba(0,0,0,0.20);
}

.zg-inkgold-dark .tab-lens {
  background: linear-gradient(145deg,
    rgba(var(--zg-primary-rgb, 201,168,76), 0.15),
    rgba(var(--zg-accent-rgb, 232,213,163), 0.08)
  );
  box-shadow:
    0 0.5px 0 0 rgba(255,243,214,0.12),
    0 1px 2px rgba(0,0,0,0.15),
    0 4px 12px -4px rgba(0,0,0,0.20);
}

.zg-inkgold-dark .tab { color: rgba(255,243,214,0.45); opacity: 0.6; }
.zg-inkgold-dark .tab.on { color: var(--zg-primary-2); opacity: 1; }
</style>
