<!-- Generated by Trae Work -->
<!--
  移动端悬浮药丸底栏 v2
  - iOS 26 Liquid Glass 风格
  - JS动态测量tab位置，滑动指示器永远精确不错位
  - spring弹性动效 cubic-bezier(0.34, 1.56, 0.64, 1)
  - 无完整边框，只有顶部高光
-->
<template>
  <nav class="tabbar" v-if="isMobile">
    <div class="tabbar-inner" ref="barRef">
      <!-- 滑动药丸指示器：用JS动态测量位置，永远精确 -->
      <div
        class="tab-pill"
        :style="{ transform: `translateX(${pill.x}px)`, width: `${pill.w}px`, height: `${pill.h}px` }"
      />
      <button
        v-for="(t, i) in tabs"
        :key="t.to"
        class="tab"
        :class="{ on: activeIndex === i }"
        :ref="el => setTabRef(el, i)"
        @click="go(t.to)"
      >
        <span class="t-ic" v-html="t.ic"></span>
        <span class="t-lb">{{ t.lb }}</span>
      </button>
    </div>
  </nav>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, nextTick, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useUserStore } from '@/store/user'

const route = useRoute()
const router = useRouter()
const user = useUserStore()
const barRef = ref<HTMLElement | null>(null)
const tabRefs = ref<(HTMLElement | null)[]>([])

const setTabRef = (el: any, i: number) => {
  if (el) tabRefs.value[i] = el
}

const allTabs = [
  { to: '/', lb: '首页', ic: '🏠', roles: ['SUPER_ADMIN','TEACHER','STUDENT'] },
  { to: '/subjects', lb: '科目', ic: '📚', roles: ['SUPER_ADMIN','TEACHER','STUDENT'] },
  { to: '/guide', lb: '指南', ic: '🧭', roles: ['SUPER_ADMIN','TEACHER','STUDENT'] },
  { to: '/profile', lb: '我的', ic: '👤', roles: ['SUPER_ADMIN','TEACHER','STUDENT'] },
  { to: '/admin', lb: '管理', ic: '⚙️', roles: ['SUPER_ADMIN','TEACHER'] },
]

const tabs = computed(() => allTabs.filter(t => t.roles.includes((user as any).role || 'STUDENT')))

const activeIndex = computed(() => {
  const p = route.path
  const idx = tabs.value.findIndex(t => {
    if (t.to === '/') return p === '/'
    return p.startsWith(t.to)
  })
  return idx >= 0 ? idx : 0
})

// 药丸指示器位置和大小
const pill = ref({ x: 0, w: 0, h: 40 })

// 测量并更新药丸位置
const measurePill = () => {
  if (!barRef.value) return
  const bar = barRef.value
  const activeEl = tabRefs.value[activeIndex.value]
  if (!activeEl) return

  const barRect = bar.getBoundingClientRect()
  const elRect = activeEl.getBoundingClientRect()

  // 计算在bar内的相对位置
  const x = elRect.left - barRect.left
  // 药丸宽度比tab稍小，留出内边距
  const w = Math.max(48, elRect.width - 12)
  // 居中偏移
  const offsetX = (elRect.width - w) / 2

  pill.value = {
    x: x + offsetX,
    w: w,
    h: 40
  }
}

// 监听路由变化更新药丸
watch(activeIndex, () => {
  nextTick(() => measurePill())
})

let ro: ResizeObserver | null = null

const isMobile = ref(false)
const check = () => { isMobile.value = window.innerWidth <= 768 }

onMounted(() => {
  check()
  window.addEventListener('resize', () => {
    check()
    measurePill()
  })
  nextTick(() => {
    measurePill()
    if (window.ResizeObserver && barRef.value) {
      ro = new ResizeObserver(() => measurePill())
      ro.observe(barRef.value)
      tabRefs.value.forEach(el => el && ro?.observe(el))
    }
  })
})

onUnmounted(() => {
  window.removeEventListener('resize', check)
  window.removeEventListener('resize', measurePill)
  ro?.disconnect()
})

function go(to: string) { router.push(to) }
</script>

<style scoped>
.tabbar {
  display: block;
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  z-index: 200;
  padding: 0 12px calc(16px + env(safe-area-inset-bottom));
  pointer-events: none;
}

.tabbar-inner {
  pointer-events: auto;
  position: relative;
  display: flex;
  align-items: center;
  justify-content: space-around;
  height: 58px;
  padding: 4px 6px;
  border-radius: 29px;
  /* iOS 26 Liquid Glass 材质：无完整边框，顶部高光+多层阴影 */
  background: rgba(255, 255, 255, 0.72);
  -webkit-backdrop-filter: blur(40px) saturate(150%);
  backdrop-filter: blur(40px) saturate(150%);
  box-shadow:
    inset 0 0.5px 0.5px rgba(255, 255, 255, 0.9),
    0 0 0 0.5px rgba(255, 255, 255, 0.3),
    0 1px 2px rgba(0, 0, 0, 0.03),
    0 8px 32px -8px rgba(0, 0, 0, 0.10),
    0 20px 48px -20px rgba(0, 0, 0, 0.08);
}

/* 滑动药丸指示器：Liquid Glass 风格金色磨砂药丸 */
.tab-pill {
  position: absolute;
  top: 50%;
  left: 6px;
  height: 40px;
  border-radius: 20px;
  background: linear-gradient(145deg, rgba(var(--zg-primary-rgb, 201, 168, 76), 0.15), rgba(var(--zg-accent-rgb, 232, 213, 163), 0.12));
  box-shadow:
    inset 0 0.5px 0.5px rgba(255, 255, 255, 0.8),
    inset 0 0 0 0.5px rgba(var(--zg-primary-rgb, 201, 168, 76), 0.2),
    0 1px 3px rgba(var(--zg-primary-rgb, 201, 168, 76), 0.10);
  transform: translateX(0);
  transition: transform 0.45s cubic-bezier(0.34, 1.56, 0.64, 1),
              width 0.45s cubic-bezier(0.34, 1.56, 0.64, 1);
  margin-top: -20px;
  z-index: 0;
  pointer-events: none;
}

.tab {
  position: relative;
  z-index: 1;
  flex: 1;
  min-width: 0;
  height: 50px;
  border: none;
  background: transparent;
  cursor: pointer;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 2px;
  color: var(--zg-text-dim, #6b7280);
  transition: color 0.3s cubic-bezier(0.22, 1, 0.36, 1),
              transform 0.3s cubic-bezier(0.34, 1.56, 0.64, 1);
  -webkit-tap-highlight-color: transparent;
  user-select: none;
  padding: 0;
  font-family: inherit;
}

.t-ic {
  font-size: 20px;
  line-height: 1;
  filter: grayscale(0.3);
  transition: transform 0.4s cubic-bezier(0.34, 1.56, 0.64, 1),
              filter 0.3s ease;
}

.t-lb {
  font-size: 10px;
  font-weight: 500;
  line-height: 1;
  letter-spacing: 0.02em;
  transition: font-weight 0.3s ease, color 0.3s ease;
}

.tab.on {
  color: var(--zg-primary, #c9a84c);
}

.tab.on .t-ic {
  filter: grayscale(0);
  transform: scale(1.15) translateY(-1px);
}

.tab.on .t-lb {
  font-weight: 700;
}

.tab:active {
  transform: scale(0.92);
}

/* 深色模式适配 */
.zg-inkgold-dark .tabbar-inner {
  background: rgba(44, 36, 24, 0.78);
  box-shadow:
    inset 0 0.5px 0.5px rgba(255, 243, 214, 0.12),
    0 0 0 0.5px rgba(255, 243, 214, 0.08),
    0 1px 2px rgba(0, 0, 0, 0.20),
    0 8px 32px -8px rgba(0, 0, 0, 0.35),
    0 20px 48px -20px rgba(0, 0, 0, 0.28);
}

.zg-inkgold-dark .tab-pill {
  background: linear-gradient(145deg, rgba(var(--zg-primary-rgb, 201, 168, 76), 0.22), rgba(var(--zg-accent-rgb, 232, 213, 163), 0.14));
  box-shadow:
    inset 0 0.5px 0.5px rgba(255, 243, 214, 0.15),
    inset 0 0 0 0.5px rgba(var(--zg-primary-rgb, 201, 168, 76), 0.25),
    0 2px 6px rgba(0, 0, 0, 0.20);
}

.zg-inkgold-dark .tab { color: rgba(255, 243, 214, 0.5); }
.zg-inkgold-dark .tab.on { color: var(--zg-primary-2, #d4b96a); }
</style>
