<!-- Generated by Trae Work -->
<!-- 追光 · 移动端悬浮底栏（Floating Dock）
     设计参考：iOS 26 Liquid Glass、进化极简·微光玻璃风格
     特点：
     1. 真正悬浮：底部留白，不贴屏幕边缘
     2. 真液态玻璃：暖金细边框+柔和阴影+内顶高光
     3. 精致SVG线性图标（学术雅致，无emoji）
     4. JS精确测量滑动透镜位置
     5. 弹簧动效自然流畅 -->
<template>
  <nav class="tabbar" v-if="isMobile">
    <div class="tabbar-dock" ref="barRef">
      <!-- 滑动透镜：选中项的聚焦效果 -->
      <div
        class="tab-lens"
        :style="{ transform: `translate3d(${pill.x}px, 0, 0)`, width: `${pill.w}px` }"
      />
      <button
        v-for="(t, i) in tabs"
        :key="t.key || t.to"
        class="tab"
        :class="{ on: activeIndex === i, notify: t.key === 'notice' }"
        :ref="el => setTabRef(el, i)"
        @click="handleTab(t)"
      >
        <span class="t-ic-wrap">
          <el-badge v-if="t.key === 'notice'" :value="unread" :hidden="unread === 0" :max="99" class="tab-badge">
            <svg class="t-ic" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">
              <component :is="t.icon" />
            </svg>
          </el-badge>
          <svg v-else class="t-ic" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">
            <component :is="t.icon" />
          </svg>
        </span>
        <span class="t-lb">{{ t.lb }}</span>
      </button>
    </div>
  </nav>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, nextTick, watch, h } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useUserStore } from '@/store/user'
import { api } from '@/api'

const route = useRoute()
const router = useRouter()
const user = useUserStore()
const barRef = ref<HTMLElement | null>(null)
const tabRefs = ref<(HTMLElement | null)[]>([])

const unread = ref(0)

async function refreshNoticeUnread() {
  if (!user.isLogin) { unread.value = 0; return }
  try {
    const notices: any = await api.notices()
    unread.value = (notices || []).filter((n: any) => !n.read).length
  } catch { unread.value = 0 }
}

const setTabRef = (el: any, i: number) => {
  if (el) tabRefs.value[i] = el
}

// SVG 线性图标 - 雅致学术风格，1.6px stroke，圆角线帽
const IconHome = () => [
  h('path', { d: 'M3 9.5L12 3l9 6.5' }),
  h('path', { d: 'M5 8.5V19a1 1 0 001 1h4v-5h4v5h4a1 1 0 001-1V8.5' })
]
const IconBook = () => [
  h('path', { d: 'M4 19v-14.5A2.5 2.5 0 016.5 2H20v18H6.5A2.5 2.5 0 004 22.5' }),
  h('path', { d: 'M4 19a2.5 2.5 0 012.5-2H20' })
]
const IconBell = () => [
  h('path', { d: 'M18 8A6 6 0 006 8c0 7-3 9-3 9h18s-3-2-3-9' }),
  h('path', { d: 'M13.73 21a2 2 0 01-3.46 0' })
]
const IconUser = () => [
  h('path', { d: 'M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2' }),
  h('circle', { cx: '12', cy: '7', r: '3.5' })
]
const IconSettings = () => [
  h('circle', { cx: '12', cy: '12', r: '2.5' }),
  h('path', { d: 'M19.4 15a1.65 1.65 0 00.33 1.82l.06.06a2 2 0 01-2.83 2.83l-.06-.06a1.65 1.65 0 00-1.82-.33 1.65 1.65 0 00-1 1.51V21a2 2 0 01-4 0v-.09A1.65 1.65 0 009 19.4a1.65 1.65 0 00-1.82.33l-.06.06a2 2 0 01-2.83-2.83l.06-.06a1.65 1.65 0 00.33-1.82 1.65 1.65 0 00-1.51-1H3a2 2 0 010-4h.09A1.65 1.65 0 004.6 9a1.65 1.65 0 00-.33-1.82l-.06-.06a2 2 0 012.83-2.83l.06.06a1.65 1.65 0 001.82.33H9a1.65 1.65 0 001-1.51V3a2 2 0 014 0v.09a1.65 1.65 0 001 1.51 1.65 1.65 0 001.82-.33l.06-.06a2 2 0 012.83 2.83l-.06.06a1.65 1.65 0 00-.33 1.82V9a1.65 1.65 0 001.51 1H21a2 2 0 010 4h-.09a1.65 1.65 0 00-1.51 1z' })
]

const baseTabs = [
  { to: '/', lb: '首页', icon: IconHome, roles: ['SUPER_ADMIN','TEACHER','STUDENT'] },
  { to: '/subjects', lb: '科目', icon: IconBook, roles: ['SUPER_ADMIN','TEACHER','STUDENT'] },
  { key: 'notice', lb: '通知', icon: IconBell, roles: ['SUPER_ADMIN','TEACHER','STUDENT'] },
  { to: '/profile', lb: '我的', icon: IconUser, roles: ['SUPER_ADMIN','TEACHER','STUDENT'] },
  { to: '/admin', lb: '管理', icon: IconSettings, roles: ['SUPER_ADMIN','TEACHER'] },
]

const tabs = computed(() => baseTabs.filter(t => t.roles.includes((user as any).role || 'STUDENT')))

const activeIndex = computed(() => {
  const p = route.path
  const idx = tabs.value.findIndex(t => {
    if (t.key === 'notice' || !t.to) return false
    if (t.to === '/') return p === '/'
    return p.startsWith(t.to)
  })
  return idx >= 0 ? idx : 0
})

// 药丸透镜位置 - 精确测量
const pill = ref({ x: 0, w: 0 })

const measurePill = () => {
  if (!barRef.value) return
  const bar = barRef.value
  const activeEl = tabRefs.value[activeIndex.value]
  if (!activeEl) return

  const barRect = bar.getBoundingClientRect()
  const elRect = activeEl.getBoundingClientRect()

  // 透镜比tab略小，形成聚焦效果
  const x = elRect.left - barRect.left
  const w = elRect.width - 12
  const offsetX = (elRect.width - w) / 2

  pill.value = { x: x + offsetX, w: w }
}

watch(activeIndex, () => { nextTick(() => measurePill()) })

let ro: ResizeObserver | null = null
const isMobile = ref(false)

const check = () => { isMobile.value = window.innerWidth <= 768 }

onMounted(() => {
  check()
  const onResize = () => { check(); measurePill() }
  window.addEventListener('resize', onResize)
  window.addEventListener('messages-read', refreshNoticeUnread)
  refreshNoticeUnread()
  nextTick(() => {
    measurePill()
    if (window.ResizeObserver && barRef.value) {
      ro = new ResizeObserver(() => measurePill())
      ro.observe(barRef.value)
      tabRefs.value.forEach(el => el && ro?.observe(el))
    }
  })
})

onUnmounted(() => {
  window.removeEventListener('resize', check)
  window.removeEventListener('messages-read', refreshNoticeUnread)
  ro?.disconnect()
})

function handleTab(t: any) {
  if (t.key === 'notice') {
    window.dispatchEvent(new CustomEvent('zg-open-notice'))
    return
  }
  router.push(t.to)
}
</script>

<style scoped>
/* ===== v17.1 真液态玻璃悬浮 Dock（完整胶囊形状）===== */
.tabbar {
  display: block !important;
  position: fixed !important;
  bottom: 0 !important;
  left: 0 !important;
  right: 0 !important;
  z-index: 200 !important;
  padding: 0 16px calc(16px + env(safe-area-inset-bottom)) 16px !important;
  pointer-events: none !important;
  background: transparent !important;
  border: none !important;
  box-shadow: none !important;
}

.tabbar-dock {
  pointer-events: auto !important;
  position: relative !important;
  display: flex !important;
  align-items: center !important;
  justify-content: center !important;
  width: fit-content !important;
  min-width: 280px !important;
  height: 58px !important;
  margin: 0 auto !important;
  padding: 4px !important;
  border-radius: 29px !important;
  /* L1层真液态玻璃 */
  background: linear-gradient(165deg, var(--zg-glass-1-bg), var(--zg-glass-1-bg-2)) !important;
  -webkit-backdrop-filter: blur(var(--zg-glass-blur)) saturate(var(--zg-glass-sat)) !important;
  backdrop-filter: blur(var(--zg-glass-blur)) saturate(var(--zg-glass-sat)) !important;
  border: 1px solid var(--zg-glass-1-border) !important;
  box-shadow: var(--zg-glass-1-shadow) !important;
  overflow: hidden !important;
  transition: transform .4s var(--zg-spring);
}
/* 顶部1px细高光条 */
.tabbar-dock::before {
  content: '';
  position: absolute !important;
  top: 0;
  left: 10%;
  right: 10%;
  height: 1px;
  background: linear-gradient(90deg, transparent, rgba(255,255,255,0.5), transparent);
  pointer-events: none !important;
  z-index: 1;
}
/* 深色档高光 */
.zg-inkgold-dark .tabbar-dock::before {
  background: linear-gradient(90deg, transparent, rgba(255,243,214,0.4), transparent);
}

/* 滑动透镜 */
.tab-lens {
  position: absolute !important;
  top: 4px !important;
  left: 4px !important;
  height: 50px !important;
  border-radius: 25px !important;
  background: linear-gradient(145deg,
    rgba(255,255,255,0.25),
    rgba(255,250,230,0.10)
  ) !important;
  box-shadow:
    inset 0 1px 0 rgba(255,255,255,0.35) !important,
    0 2px 8px -2px rgba(184,148,63,0.10) !important;
  transform: translate3d(0, 0, 0) !important;
  transition: transform 0.55s var(--zg-spring),
              width 0.55s var(--zg-spring) !important;
  z-index: 0 !important;
  pointer-events: none !important;
  will-change: transform, width !important;
}

.tab {
  position: relative !important;
  z-index: 2 !important;
  flex: 1 1 0 !important;
  min-width: 0 !important;
  min-height: 50px !important;
  border: none !important;
  background: transparent !important;
  cursor: pointer !important;
  display: flex !important;
  flex-direction: column !important;
  align-items: center !important;
  justify-content: center !important;
  gap: 3px !important;
  color: var(--zg-text-dim) !important;
  opacity: 0.7 !important;
  transition: color 0.3s var(--zg-ease),
              opacity 0.3s var(--zg-ease),
              transform 0.4s var(--zg-spring) !important;
  -webkit-tap-highlight-color: transparent !important;
  user-select: none !important;
  padding: 0 4px !important;
  font-family: inherit !important;
  border-radius: 25px !important;
}

.t-ic-wrap {
  display: flex !important;
  align-items: center !important;
  justify-content: center !important;
  width: 24px !important;
  height: 24px !important;
  transition: transform 0.35s cubic-bezier(0.34, 1.56, 0.64, 1) !important;
}

.t-ic {
  width: 22px !important;
  height: 22px !important;
  transition: transform 0.35s cubic-bezier(0.34, 1.56, 0.64, 1),
              stroke-width 0.25s ease !important;
}

.tab-badge :deep(.el-badge__content) {
  font-size: 9px !important;
  height: 14px !important;
  line-height: 14px !important;
  padding: 0 4px !important;
  border: none !important;
}

.t-lb {
  font-size: 10px !important;
  font-weight: 500 !important;
  line-height: 1 !important;
  letter-spacing: 0.02em !important;
  transition: font-weight 0.25s ease,
              color 0.25s ease,
              transform 0.35s cubic-bezier(0.34, 1.56, 0.64, 1) !important;
}

.tab.on {
  color: #B8943F !important;
  opacity: 1 !important;
}

.tab.on .t-ic-wrap {
  transform: translateY(-1px) !important;
}

.tab.on .t-ic {
  transform: scale(1.08) !important;
  stroke-width: 2 !important;
}

.tab.on .t-lb {
  font-weight: 600 !important;
}

.tab:active {
  transform: scale(0.92) !important;
}

/* ===== 深色模式 ===== */
.zg-inkgold-dark .tabbar-dock {
  background: linear-gradient(165deg, var(--zg-glass-1-bg), var(--zg-glass-1-bg-2)) !important;
  -webkit-backdrop-filter: blur(24px) saturate(180%) !important;
  backdrop-filter: blur(24px) saturate(180%) !important;
  border: 1px solid var(--zg-glass-1-border) !important;
  box-shadow: var(--zg-glass-1-shadow) !important;
}

.zg-inkgold-dark .tab-lens {
  background: linear-gradient(145deg,
    rgba(212,175,55,0.12),
    rgba(230,198,110,0.06)
  ) !important;
  box-shadow:
    inset 0 1px 0 rgba(255,243,214,0.15) !important,
    inset 0 -1px 0 rgba(0,0,0,0.08) !important,
    0 2px 8px -2px rgba(0,0,0,0.15) !important;
}

.zg-inkgold-dark .tab { color: rgba(255,243,214,0.5) !important; opacity: 0.65 !important; }
.zg-inkgold-dark .tab.on { color: #D4AF37 !important; opacity: 1 !important; }

/* 经典暖橘模式：贴边样式 */
html:not(.zg-inkgold) .tabbar-dock {
  background: linear-gradient(180deg, rgba(255,251,244,0.95), rgba(245,239,226,0.98)) !important;
  -webkit-backdrop-filter: blur(20px) saturate(150%) !important;
  backdrop-filter: blur(20px) saturate(150%) !important;
  box-shadow: 0 -4px 20px rgba(245,158,11,0.12) !important;
  border: 1px solid rgba(245,158,11,0.15) !important;
  border-radius: 29px !important;
  width: fit-content !important;
  max-width: 360px !important;
  min-width: 280px !important;
  margin: 0 auto !important;
  height: 58px !important;
  padding: 4px !important;
}
html:not(.zg-inkgold) .tabbar-dock::before { display: none !important; }
html:not(.zg-inkgold) .tabbar {
  padding: 0 16px calc(16px + env(safe-area-inset-bottom)) 16px !important;
}
html:not(.zg-inkgold) .tab-lens {
  background: linear-gradient(145deg, rgba(245,158,11,0.12), rgba(251,191,36,0.06)) !important;
  box-shadow: 0 2px 8px -2px rgba(245,158,11,0.15) !important;
  border-radius: 25px !important;
}
html:not(.zg-inkgold) .tab { color: #92400E !important; opacity: 0.6 !important; border-radius: 25px !important; }
html:not(.zg-inkgold) .tab.on { color: #F59E0B !important; opacity: 1 !important; }
</style>
