<!-- Generated by Trae Work -->
<!-- 追光 · 顶部导航栏（NavBar）
     2026 进化极简·微光玻璃风格 -->
<template>
  <header class="nav" v-if="showNav">
    <div class="nav-inner">
      <div class="nav-left" @click="goHome" style="cursor:pointer">
        <span class="nav-logo">
          <svg viewBox="0 0 32 32" width="28" height="28" fill="none">
            <circle cx="16" cy="16" r="14" stroke="url(#g1)" stroke-width="2"/>
            <path d="M11 20 C11 14, 21 14, 21 20" stroke="url(#g2)" stroke-width="2" stroke-linecap="round"/>
            <circle cx="16" cy="12" r="3" fill="url(#g2)"/>
            <defs>
              <linearGradient id="g1" x1="0" y1="0" x2="32" y2="32">
                <stop offset="0%" stop-color="#DFC98A"/>
                <stop offset="100%" stop-color="#B8943F"/>
              </linearGradient>
              <linearGradient id="g2" x1="11" y1="9" x2="21" y2="20">
                <stop offset="0%" stop-color="#C9A95A"/>
                <stop offset="100%" stop-color="#B8943F"/>
              </linearGradient>
            </defs>
          </svg>
        </span>
        <span class="nav-brand zg-grad-text">追光</span>
      </div>

      <nav class="nav-links" v-if="!isMobile">
        <router-link v-for="link in visibleLinks" :key="link.to" :to="link.to" class="nav-link" active-class="on">
          {{ link.label }}
        </router-link>
      </nav>

      <div class="nav-right">
        <button class="nav-icon-btn" @click="toggleTheme" :title="isInkgold ? '切换到经典模式' : '切换到墨金模式'">
          <svg v-if="isInkgold" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">
            <circle cx="12" cy="12" r="4"/>
            <path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M6.34 17.66l-1.41 1.41M19.07 4.93l-1.41 1.41"/>
          </svg>
          <svg v-else width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">
            <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/>
          </svg>
        </button>
        <div class="nav-user" @click="goProfile" v-if="user.isLogin" :title="user.current?.realName || user.current?.username">
          <img v-if="user.current?.avatar" :src="user.current.avatar" class="nav-avatar" alt="avatar"/>
          <div v-else class="nav-avatar nav-avatar-fallback">{{ (user.current?.realName || user.current?.username || '?').charAt(0).toUpperCase() }}</div>
        </div>
      </div>
    </div>
  </header>
</template>

<script setup lang="ts">
import { computed, ref, onMounted, onUnmounted } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { useUserStore } from '@/store/user'
import { useSettingsStore } from '@/store/settings'

const router = useRouter()
const route = useRoute()
const user = useUserStore()
const settings = useSettingsStore()

const isMobile = ref(false)
const showNav = computed(() => !route.meta.hideNav)
const isInkgold = computed(() => settings.designMode === 'inkgold')

const allLinks = [
  { to: '/', label: '首页', roles: ['SUPER_ADMIN','TEACHER','STUDENT'] },
  { to: '/subjects', label: '科目', roles: ['SUPER_ADMIN','TEACHER','STUDENT'] },
  { to: '/blog', label: '美文', roles: ['SUPER_ADMIN','TEACHER','STUDENT'] },
  { to: '/leaderboard', label: '排行', roles: ['SUPER_ADMIN','TEACHER','STUDENT'] },
  { to: '/guide', label: '指南', roles: ['SUPER_ADMIN','TEACHER','STUDENT'] },
  { to: '/query', label: '查询', roles: ['SUPER_ADMIN','TEACHER','STUDENT'] },
  { to: '/admin', label: '管理', roles: ['SUPER_ADMIN','TEACHER'] },
]

const visibleLinks = computed(() => allLinks.filter(l => l.roles.includes((user as any).current?.role || 'STUDENT')))

function goHome() { router.push('/') }
function goProfile() { router.push('/profile') }
function toggleTheme() {
  settings.setDesignMode(settings.designMode === 'inkgold' ? 'classic' : 'inkgold')
}

function checkMobile() { isMobile.value = window.innerWidth <= 768 }

onMounted(() => {
  checkMobile()
  window.addEventListener('resize', checkMobile)
})
onUnmounted(() => window.removeEventListener('resize', checkMobile))
</script>

<style scoped>
/* ===== 2026 进化极简·微光玻璃 导航栏 =====
   L1导航层：极薄填充+大模糊+细描边+柔影 */
.nav {
  position: sticky !important;
  top: 0 !important;
  z-index: 100 !important;
  border-radius: 0 !important;
  border: none !important;
  background: linear-gradient(180deg, rgba(255,255,255,0.06), rgba(255,253,248,0.04)) !important;
  -webkit-backdrop-filter: blur(24px) saturate(140%) !important;
  backdrop-filter: blur(24px) saturate(140%) !important;
  box-shadow:
    0 0 0 0.5px rgba(255,255,255,0.3) !important,
    0 1px 1px rgba(100,80,40,0.02) !important,
    0 4px 16px -8px rgba(100,80,40,0.05) !important;
  padding-top: env(safe-area-inset-top);
  transition: box-shadow .3s cubic-bezier(0.25, 0.1, 0.25, 1),
              background .3s ease !important;
}

.nav-inner {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 24px;
  height: 56px;
  display: flex;
  align-items: center;
  gap: 24px;
}

.nav-left {
  display: flex;
  align-items: center;
  gap: 10px;
  flex-shrink: 0;
}

.nav-logo {
  display: flex;
  align-items: center;
  justify-content: center;
}

.nav-brand {
  font-size: 20px;
  font-weight: 800;
  letter-spacing: 2px;
  font-family: 'Noto Serif SC', 'Source Han Serif SC', 'Songti SC', serif;
}

.nav-links {
  display: flex;
  align-items: center;
  gap: 4px;
  flex: 1;
  justify-content: center;
}

.nav-link {
  padding: 8px 16px;
  border-radius: 10px;
  font-size: 14px;
  font-weight: 500;
  color: var(--zg-text-dim, #786E60);
  text-decoration: none;
  transition: color .2s ease, background .2s ease, transform .2s ease;
  position: relative;
}

.nav-link:hover {
  color: var(--zg-text, #2A2520);
  background: rgba(184,148,63,0.06);
}

.nav-link.on {
  color: var(--zg-primary, #B8943F);
  font-weight: 600;
}

.nav-link.on::after {
  content: '';
  position: absolute;
  bottom: 2px;
  left: 50%;
  transform: translateX(-50%);
  width: 16px;
  height: 2px;
  border-radius: 2px;
  background: linear-gradient(90deg, var(--zg-accent, #DFC98A), var(--zg-primary, #B8943F));
}

.nav-right {
  display: flex;
  align-items: center;
  gap: 8px;
  flex-shrink: 0;
}

.nav-icon-btn {
  position: relative;
  width: 36px;
  height: 36px;
  border-radius: 10px;
  border: none;
  background: transparent;
  color: var(--zg-text-dim, #786E60);
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: background .2s ease, color .2s ease, transform .2s ease;
}

.nav-icon-btn:hover {
  background: rgba(184,148,63,0.08);
  color: var(--zg-primary, #B8943F);
}

.nav-icon-btn:active { transform: scale(0.92); }

.nav-user {
  cursor: pointer;
  margin-left: 4px;
  transition: transform .2s ease;
}
.nav-user:hover { transform: scale(1.05); }
.nav-user:active { transform: scale(0.95); }

.nav-avatar {
  width: 32px;
  height: 32px;
  border-radius: 50%;
  object-fit: cover;
  border: 1.5px solid rgba(184,148,63,0.2);
}

.nav-avatar-fallback {
  display: flex;
  align-items: center;
  justify-content: center;
  background: linear-gradient(135deg, rgba(184,148,63,0.15), rgba(223,201,138,0.10));
  color: var(--zg-primary, #B8943F);
  font-weight: 600;
  font-size: 13px;
}

/* 墨金深色模式导航栏 */
.zg-inkgold-dark .nav {
  background: linear-gradient(180deg, rgba(32,27,20,0.18), rgba(26,22,16,0.12)) !important;
  -webkit-backdrop-filter: blur(24px) saturate(140%) !important;
  backdrop-filter: blur(24px) saturate(140%) !important;
  box-shadow:
    0 0 0 0.5px rgba(255,243,214,0.08) !important,
    0 1px 1px rgba(0,0,0,0.08) !important,
    0 4px 16px -8px rgba(0,0,0,0.18) !important;
}

/* 经典暖橘模式：保持原有风格 */
html:not(.zg-inkgold) .nav {
  background: linear-gradient(180deg, rgba(255,255,255,0.88), rgba(255,248,240,0.82)) !important;
  -webkit-backdrop-filter: blur(20px) saturate(150%) !important;
  backdrop-filter: blur(20px) saturate(150%) !important;
  box-shadow: 0 1px 3px rgba(245,158,11,0.08) !important;
}
html:not(.zg-inkgold) .nav-link { color: #78350F; }
html:not(.zg-inkgold) .nav-link.on { color: #F59E0B; }
html:not(.zg-inkgold) .nav-icon-btn { color: #92400E; }
html:not(.zg-inkgold) .nav-icon-btn:hover { color: #F59E0B; background: rgba(245,158,11,0.08); }
html:not(.zg-inkgold) .nav-avatar-fallback { background: linear-gradient(135deg, rgba(245,158,11,0.15), rgba(251,146,60,0.10)); color: #F59E0B; }
html:not(.zg-inkgold) .nav-avatar { border-color: rgba(245,158,11,0.25); }

/* 移动端适配 */
@media (max-width: 768px) {
  .nav-inner { padding: 0 16px; height: 52px; gap: 12px; }
  .nav-links { display: none; }
  .nav-brand { font-size: 18px; letter-spacing: 1.5px; }
}
</style>
